/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Request for admin login (username/password).
 */
export type AdminLoginRequest = {
  /**
   * @description Admin password.
   * @type string
   */
  password: string;
  /**
   * @description Admin username.
   * @type string
   */
  username: string;
};
