/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Response after successful admin login.
 */
export type AdminLoginResponse = {
  /**
   * @description The admin\'s username.
   * @type string
   */
  username: string;
};
