/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AdminEventResponse } from "./AdminEventResponse.ts";

/**
 * @description Response containing list of events for admin.
 */
export type AdminEventsListResponse = {
  /**
   * @type array
   */
  events: AdminEventResponse[];
};
