/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AdminLoginRequest } from "./AdminLoginRequest.ts";
import type { AdminLoginResponse } from "./AdminLoginResponse.ts";

export type AdminLogin200 = AdminLoginResponse;

/**
 * @description Invalid credentials
 */
export type AdminLogin401 = any;

/**
 * @description Admin-pending session required
 */
export type AdminLogin403 = any;

export type AdminLoginMutationRequest = AdminLoginRequest;

export type AdminLoginMutationResponse = AdminLogin200;

export type AdminLoginMutation = {
  Response: AdminLogin200;
  Request: AdminLoginMutationRequest;
  Errors: AdminLogin401 | AdminLogin403;
};
