/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AdminRsvpSummary } from "./AdminRsvpSummary.ts";

/**
 * @description Guest with invite code and RSVP status for admin view.
 */
export type AdminGuestResponse = {
  /**
   * @type string
   */
  created_at: string;
  /**
   * @type string, uuid
   */
  id: string;
  /**
   * @type string,null | undefined
   */
  invite_code?: string | null;
  /**
   * @type string
   */
  name: string;
  /**
   * @type integer, int32
   */
  party_size: number;
  /**
   * @description RSVP summary for a guest in admin view.
   * @type object
   */
  rsvp: AdminRsvpSummary;
};
