/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description RSVP summary for a guest in admin view.
 */
export type AdminRsvpSummary = {
  /**
   * @type integer, int32
   */
  attending_count: number;
  /**
   * @type boolean
   */
  has_responded: boolean;
  /**
   * @type integer, int32
   */
  not_attending_count: number;
  /**
   * @type string,null | undefined
   */
  responded_at?: string | null;
};
