/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AdminGuestResponse } from "./AdminGuestResponse.ts";

/**
 * @description Response containing list of guests for admin.
 */
export type AdminGuestsListResponse = {
  /**
   * @type array
   */
  guests: AdminGuestResponse[];
  /**
   * @type integer, int64
   */
  total: number;
};
