/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Response for a single attendee.
 */
export type AttendeeResponse = {
  /**
   * @type string,null | undefined
   */
  dietary_restrictions?: string | null;
  /**
   * @type string, uuid
   */
  id: string;
  /**
   * @type boolean
   */
  is_attending: boolean;
  /**
   * @type boolean
   */
  is_primary: boolean;
  /**
   * @type string,null | undefined
   */
  meal_preference?: string | null;
  /**
   * @type string
   */
  name: string;
};
