/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Input for a single attendee in an RSVP submission.
 */
export type AttendeeInput = {
  /**
   * @type string,null | undefined
   */
  dietary_restrictions?: string | null;
  /**
   * @type boolean
   */
  is_attending: boolean;
  /**
   * @type boolean
   */
  is_primary: boolean;
  /**
   * @type string,null | undefined
   */
  meal_preference?: string | null;
  /**
   * @type string
   */
  name: string;
};
