/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Request to change admin password.
 */
export type ChangePasswordRequest = {
  /**
   * @type string
   */
  current_password: string;
  /**
   * @type string
   */
  new_password: string;
};
