/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Response after successful password change.
 */
export type ChangePasswordResponse = {
  /**
   * @type string
   */
  message: string;
};
