/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ChangePasswordRequest } from "./ChangePasswordRequest.ts";
import type { ChangePasswordResponse } from "./ChangePasswordResponse.ts";

export type ChangePassword200 = ChangePasswordResponse;

/**
 * @description Validation error
 */
export type ChangePassword400 = any;

/**
 * @description Unauthorized or wrong password
 */
export type ChangePassword401 = any;

export type ChangePasswordMutationRequest = ChangePasswordRequest;

export type ChangePasswordMutationResponse = ChangePassword200;

export type ChangePasswordMutation = {
  Response: ChangePassword200;
  Request: ChangePasswordMutationRequest;
  Errors: ChangePassword400 | ChangePassword401;
};
