/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AdminEventResponse } from "./AdminEventResponse.ts";
import type { CreateEventRequest } from "./CreateEventRequest.ts";

export type CreateEvent201 = AdminEventResponse;

/**
 * @description Validation error
 */
export type CreateEvent400 = any;

/**
 * @description Unauthorized
 */
export type CreateEvent401 = any;

export type CreateEventMutationRequest = CreateEventRequest;

export type CreateEventMutationResponse = CreateEvent201;

export type CreateEventMutation = {
  Response: CreateEvent201;
  Request: CreateEventMutationRequest;
  Errors: CreateEvent400 | CreateEvent401;
};
