/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Request to create a new guest.
 */
export type CreateGuestRequest = {
  /**
   * @type string
   */
  name: string;
  /**
   * @type integer, int32
   */
  party_size: number;
};
