/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateGuestRequest } from "./CreateGuestRequest.ts";
import type { CreateGuestResponse } from "./CreateGuestResponse.ts";

export type CreateGuest201 = CreateGuestResponse;

/**
 * @description Validation error
 */
export type CreateGuest400 = any;

/**
 * @description Unauthorized
 */
export type CreateGuest401 = any;

export type CreateGuestMutationRequest = CreateGuestRequest;

export type CreateGuestMutationResponse = CreateGuest201;

export type CreateGuestMutation = {
  Response: CreateGuest201;
  Request: CreateGuestMutationRequest;
  Errors: CreateGuest400 | CreateGuest401;
};
