/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Response after creating a guest (includes generated invite code).
 */
export type CreateGuestResponse = {
  /**
   * @type string, uuid
   */
  id: string;
  /**
   * @type string
   */
  invite_code: string;
  /**
   * @type string
   */
  name: string;
  /**
   * @type integer, int32
   */
  party_size: number;
};
