/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RecentRsvp } from "./RecentRsvp.ts";

/**
 * @description Dashboard statistics response.
 */
export type DashboardStatsResponse = {
  /**
   * @type integer, int64
   */
  attending_count: number;
  /**
   * @type integer, int64
   */
  not_attending_count: number;
  /**
   * @type integer, int64
   */
  pending_rsvps: number;
  /**
   * @type array
   */
  recent_rsvps: RecentRsvp[];
  /**
   * @type integer, int64
   */
  rsvp_count: number;
  /**
   * @type integer, int64
   */
  total_expected_attendees: number;
  /**
   * @type integer, int64
   */
  total_guests: number;
};
