/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteGuestPathParams = {
  /**
   * @description Guest ID
   * @type string, uuid
   */
  id: string;
};

/**
 * @description Guest deleted
 */
export type DeleteGuest204 = any;

/**
 * @description Unauthorized
 */
export type DeleteGuest401 = any;

/**
 * @description Guest not found
 */
export type DeleteGuest404 = any;

export type DeleteGuestMutationResponse = DeleteGuest204;

export type DeleteGuestMutation = {
  Response: DeleteGuest204;
  PathParams: DeleteGuestPathParams;
  Errors: DeleteGuest401 | DeleteGuest404;
};
