/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteEventPathParams = {
  /**
   * @description Event ID
   * @type string, uuid
   */
  id: string;
};

/**
 * @description Event deleted
 */
export type DeleteEvent204 = any;

/**
 * @description Unauthorized
 */
export type DeleteEvent401 = any;

/**
 * @description Event not found
 */
export type DeleteEvent404 = any;

export type DeleteEventMutationResponse = DeleteEvent204;

export type DeleteEventMutation = {
  Response: DeleteEvent204;
  PathParams: DeleteEventPathParams;
  Errors: DeleteEvent401 | DeleteEvent404;
};
