/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Response for a single event.
 */
export type EventResponse = {
  /**
   * @type string,null | undefined
   */
  description?: string | null;
  /**
   * @type string
   */
  event_date: string;
  /**
   * @type string
   */
  event_time: string;
  /**
   * @type string
   */
  event_type: string;
  /**
   * @type string, uuid
   */
  id: string;
  /**
   * @type string
   */
  location_address: string;
  /**
   * @type string
   */
  location_name: string;
  /**
   * @type string
   */
  name: string;
};
