/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { EventResponse } from "./EventResponse.ts";

/**
 * @description Response containing a list of events.
 */
export type EventsListResponse = {
  /**
   * @type array
   */
  events: EventResponse[];
};
