/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description A validation error for a specific field.
 */
export type FieldError = {
  /**
   * @description The field that failed validation.
   * @type string
   */
  field: string;
  /**
   * @description A human-readable error message.
   * @type string
   */
  message: string;
};
