/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Response after generating a new invite code.
 */
export type GenerateCodeResponse = {
  /**
   * @type string
   */
  invite_code: string;
};
