/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { DashboardStatsResponse } from "./DashboardStatsResponse.ts";

export type GetDashboardStats200 = DashboardStatsResponse;

/**
 * @description Unauthorized
 */
export type GetDashboardStats401 = any;

export type GetDashboardStatsQueryResponse = GetDashboardStats200;

export type GetDashboardStatsQuery = {
  Response: GetDashboardStats200;
  Errors: GetDashboardStats401;
};
