/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RsvpStatusResponse } from "./RsvpStatusResponse.ts";

export type GetRsvpStatus200 = RsvpStatusResponse;

/**
 * @description Unauthorized
 */
export type GetRsvpStatus401 = any;

export type GetRsvpStatusQueryResponse = GetRsvpStatus200;

export type GetRsvpStatusQuery = {
  Response: GetRsvpStatus200;
  Errors: GetRsvpStatus401;
};
