/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { SessionResponse } from "./SessionResponse.ts";

export type GetSession200 = SessionResponse;

/**
 * @description Not logged in
 */
export type GetSession401 = any;

export type GetSessionQueryResponse = GetSession200;

export type GetSessionQuery = {
  Response: GetSession200;
  Errors: GetSession401;
};
