/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type Health = {
  /**
   * @type string
   */
  status: string;
};

export type Health200 = Health;

export type HealthQueryResponse = Health200;

export type HealthQuery = {
  Response: Health200;
  Errors: any;
};
