/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { EventsListResponse } from "./EventsListResponse.ts";

export type ListEvents200 = EventsListResponse;

export type ListEventsQueryResponse = ListEvents200;

export type ListEventsQuery = {
  Response: ListEvents200;
  Errors: any;
};
