/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AdminGuestsListResponse } from "./AdminGuestsListResponse.ts";

export type ListGuests200 = AdminGuestsListResponse;

/**
 * @description Unauthorized
 */
export type ListGuests401 = any;

export type ListGuestsQueryResponse = ListGuests200;

export type ListGuestsQuery = {
  Response: ListGuests200;
  Errors: ListGuests401;
};
