/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AdminEventsListResponse } from "./AdminEventsListResponse.ts";

export type ListAdminEvents200 = AdminEventsListResponse;

/**
 * @description Unauthorized
 */
export type ListAdminEvents401 = any;

export type ListAdminEventsQueryResponse = ListAdminEvents200;

export type ListAdminEventsQuery = {
  Response: ListAdminEvents200;
  Errors: ListAdminEvents401;
};
