/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description A recent RSVP entry for the dashboard.
 */
export type RecentRsvp = {
  /**
   * @type integer, int32
   */
  attending_count: number;
  /**
   * @type string
   */
  guest_name: string;
  /**
   * @type integer, int32
   */
  not_attending_count: number;
  /**
   * @type string
   */
  responded_at: string;
};
