/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GenerateCodeResponse } from "./GenerateCodeResponse.ts";

export type RegenerateCodePathParams = {
  /**
   * @description Guest ID
   * @type string, uuid
   */
  id: string;
};

export type RegenerateCode200 = GenerateCodeResponse;

/**
 * @description Unauthorized
 */
export type RegenerateCode401 = any;

/**
 * @description Guest not found
 */
export type RegenerateCode404 = any;

export type RegenerateCodeMutationResponse = RegenerateCode200;

export type RegenerateCodeMutation = {
  Response: RegenerateCode200;
  PathParams: RegenerateCodePathParams;
  Errors: RegenerateCode401 | RegenerateCode404;
};
