/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RsvpResponse } from "./RsvpResponse.ts";

/**
 * @description Response for RSVP status check.
 */
export type RsvpStatusResponse = {
  /**
   * @type string
   */
  guest_name: string;
  /**
   * @type boolean
   */
  has_responded: boolean;
  /**
   * @type integer, int32
   */
  party_size: number;
  rsvp?: null | RsvpResponse;
};
