/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AttendeeResponse } from "./AttendeeResponse.ts";

/**
 * @description Response for an RSVP with its attendees.
 */
export type RsvpResponse = {
  /**
   * @type array
   */
  attendees: AttendeeResponse[];
  /**
   * @type string, uuid
   */
  guest_id: string;
  /**
   * @type string, uuid
   */
  id: string;
  /**
   * @type string
   */
  responded_at: string;
};
