/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Response for current session info.
 */
export type SessionResponse = {
  /**
   * @description Admin ID (if admin session).
   * @type string,null | undefined, uuid
   */
  admin_id?: string | null;
  /**
   * @description Admin username (if admin session).
   * @type string,null | undefined
   */
  admin_username?: string | null;
  /**
   * @description Guest ID (if guest session).
   * @type string,null | undefined, uuid
   */
  guest_id?: string | null;
  /**
   * @description Guest name (if guest session).
   * @type string,null | undefined
   */
  guest_name?: string | null;
  /**
   * @description Session type: \"guest\", \"admin_pending\", or \"admin\".
   * @type string
   */
  session_type: string;
};
