/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RsvpResponse } from "./RsvpResponse.ts";
import type { SubmitRsvpRequest } from "./SubmitRsvpRequest.ts";

export type SubmitRsvp200 = RsvpResponse;

/**
 * @description Validation error
 */
export type SubmitRsvp400 = any;

/**
 * @description Unauthorized
 */
export type SubmitRsvp401 = any;

export type SubmitRsvpMutationRequest = SubmitRsvpRequest;

export type SubmitRsvpMutationResponse = SubmitRsvp200;

export type SubmitRsvpMutation = {
  Response: SubmitRsvp200;
  Request: SubmitRsvpMutationRequest;
  Errors: SubmitRsvp400 | SubmitRsvp401;
};
