/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AttendeeInput } from "./AttendeeInput.ts";

/**
 * @description Request to submit or update an RSVP.
 */
export type SubmitRsvpRequest = {
  /**
   * @type array
   */
  attendees: AttendeeInput[];
};
