/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AdminEventResponse } from "./AdminEventResponse.ts";
import type { UpdateEventRequest } from "./UpdateEventRequest.ts";

export type UpdateEventPathParams = {
  /**
   * @description Event ID
   * @type string, uuid
   */
  id: string;
};

export type UpdateEvent200 = AdminEventResponse;

/**
 * @description Validation error
 */
export type UpdateEvent400 = any;

/**
 * @description Unauthorized
 */
export type UpdateEvent401 = any;

/**
 * @description Event not found
 */
export type UpdateEvent404 = any;

export type UpdateEventMutationRequest = UpdateEventRequest;

export type UpdateEventMutationResponse = UpdateEvent200;

export type UpdateEventMutation = {
  Response: UpdateEvent200;
  Request: UpdateEventMutationRequest;
  PathParams: UpdateEventPathParams;
  Errors: UpdateEvent400 | UpdateEvent401 | UpdateEvent404;
};
