/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Request to update an existing event.
 */
export type UpdateEventRequest = {
  /**
   * @type string,null | undefined
   */
  description?: string | null;
  /**
   * @type integer, int32
   */
  display_order: number;
  /**
   * @description Date in YYYY-MM-DD format.
   * @type string
   */
  event_date: string;
  /**
   * @description Time in HH:MM format.
   * @type string
   */
  event_time: string;
  /**
   * @type string
   */
  event_type: string;
  /**
   * @type string
   */
  location_address: string;
  /**
   * @type string
   */
  location_name: string;
  /**
   * @type string
   */
  name: string;
};
