/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AdminGuestResponse } from "./AdminGuestResponse.ts";
import type { UpdateGuestRequest } from "./UpdateGuestRequest.ts";

export type UpdateGuestPathParams = {
  /**
   * @description Guest ID
   * @type string, uuid
   */
  id: string;
};

export type UpdateGuest200 = AdminGuestResponse;

/**
 * @description Validation error
 */
export type UpdateGuest400 = any;

/**
 * @description Unauthorized
 */
export type UpdateGuest401 = any;

/**
 * @description Guest not found
 */
export type UpdateGuest404 = any;

export type UpdateGuestMutationRequest = UpdateGuestRequest;

export type UpdateGuestMutationResponse = UpdateGuest200;

export type UpdateGuestMutation = {
  Response: UpdateGuest200;
  Request: UpdateGuestMutationRequest;
  PathParams: UpdateGuestPathParams;
  Errors: UpdateGuest400 | UpdateGuest401 | UpdateGuest404;
};
