/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { FieldError } from "./FieldError.ts";

/**
 * @description Response body for validation errors.
 */
export type ValidationErrorResponse = {
  /**
   * @description The error type.
   * @type string
   */
  error: string;
  /**
   * @description List of field-level validation errors.
   * @type array
   */
  fields: FieldError[];
};
