/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Response after validating an invite code.
 */
export type ValidateCodeResponse = {
  /**
   * @description Guest name (only for guest sessions).
   * @type string,null | undefined
   */
  guest_name?: string | null;
  /**
   * @description The type of session created: \"guest\" or \"admin_pending\".
   * @type string
   */
  session_type: string;
};
