/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Request to validate an invite code.
 */
export type ValidateCodeRequest = {
  /**
   * @description The invite code to validate.
   * @type string
   */
  code: string;
};
