/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ValidateCodeRequest } from "./ValidateCodeRequest.ts";
import type { ValidateCodeResponse } from "./ValidateCodeResponse.ts";

export type ValidateCode200 = ValidateCodeResponse;

/**
 * @description Invalid code
 */
export type ValidateCode400 = any;

export type ValidateCodeMutationRequest = ValidateCodeRequest;

export type ValidateCodeMutationResponse = ValidateCode200;

export type ValidateCodeMutation = {
  Response: ValidateCode200;
  Request: ValidateCodeMutationRequest;
  Errors: ValidateCode400;
};
