/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  AdminLoginMutationRequest,
  AdminLoginMutationResponse,
  AdminLogin401,
  AdminLogin403,
} from "../types/AdminLogin.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function useGetAdminLoginUrl() {
  const res = { method: "POST", url: `/api/auth/admin/login` as const };
  return res;
}

/**
 * @summary POST /auth/admin/login - Admin login with username/password.
 * {@link /auth/admin/login}
 */
export async function useAdminLogin(
  data: AdminLoginMutationRequest,
  config: Partial<RequestConfig<AdminLoginMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    AdminLoginMutationResponse,
    ResponseErrorConfig<AdminLogin401 | AdminLogin403>,
    AdminLoginMutationRequest
  >({
    method: "POST",
    url: useGetAdminLoginUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
