/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  CreateGuestMutationRequest,
  CreateGuestMutationResponse,
  CreateGuest400,
  CreateGuest401,
} from "../types/CreateGuest.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function useGetCreateGuestUrl() {
  const res = { method: "POST", url: `/api/admin/guests` as const };
  return res;
}

/**
 * @summary POST /admin/guests - Create a new guest with an invite code.
 * {@link /admin/guests}
 */
export async function useCreateGuest(
  data: CreateGuestMutationRequest,
  config: Partial<RequestConfig<CreateGuestMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    CreateGuestMutationResponse,
    ResponseErrorConfig<CreateGuest400 | CreateGuest401>,
    CreateGuestMutationRequest
  >({
    method: "POST",
    url: useGetCreateGuestUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
