/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  CreateEventMutationRequest,
  CreateEventMutationResponse,
  CreateEvent400,
  CreateEvent401,
} from "../types/CreateEvent.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function useGetCreateEventUrl() {
  const res = { method: "POST", url: `/api/admin/events` as const };
  return res;
}

/**
 * @summary POST /admin/events - Create a new event.
 * {@link /admin/events}
 */
export async function useCreateEvent(
  data: CreateEventMutationRequest,
  config: Partial<RequestConfig<CreateEventMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    CreateEventMutationResponse,
    ResponseErrorConfig<CreateEvent400 | CreateEvent401>,
    CreateEventMutationRequest
  >({
    method: "POST",
    url: useGetCreateEventUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
