/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  ChangePasswordMutationRequest,
  ChangePasswordMutationResponse,
  ChangePassword400,
  ChangePassword401,
} from "../types/ChangePassword.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function useGetChangePasswordUrl() {
  const res = { method: "POST", url: `/api/admin/settings/password` as const };
  return res;
}

/**
 * @summary POST /admin/settings/password - Change admin password.
 * {@link /admin/settings/password}
 */
export async function useChangePassword(
  data: ChangePasswordMutationRequest,
  config: Partial<RequestConfig<ChangePasswordMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    ChangePasswordMutationResponse,
    ResponseErrorConfig<ChangePassword400 | ChangePassword401>,
    ChangePasswordMutationRequest
  >({
    method: "POST",
    url: useGetChangePasswordUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
