/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  DeleteGuestMutationResponse,
  DeleteGuestPathParams,
  DeleteGuest401,
  DeleteGuest404,
} from "../types/DeleteGuest.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function useGetDeleteGuestUrl(id: DeleteGuestPathParams["id"]) {
  const res = { method: "DELETE", url: `/api/admin/guests/${id}` as const };
  return res;
}

/**
 * @summary DELETE /admin/guests/:id - Delete a guest and their invite codes.
 * {@link /admin/guests/:id}
 */
export async function useDeleteGuest(
  id: DeleteGuestPathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    DeleteGuestMutationResponse,
    ResponseErrorConfig<DeleteGuest401 | DeleteGuest404>,
    unknown
  >({
    method: "DELETE",
    url: useGetDeleteGuestUrl(id).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
