/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  DeleteEventMutationResponse,
  DeleteEventPathParams,
  DeleteEvent401,
  DeleteEvent404,
} from "../types/DeleteEvent.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function useGetDeleteEventUrl(id: DeleteEventPathParams["id"]) {
  const res = { method: "DELETE", url: `/api/admin/events/${id}` as const };
  return res;
}

/**
 * @summary DELETE /admin/events/:id - Delete an event.
 * {@link /admin/events/:id}
 */
export async function useDeleteEvent(
  id: DeleteEventPathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    DeleteEventMutationResponse,
    ResponseErrorConfig<DeleteEvent401 | DeleteEvent404>,
    unknown
  >({
    method: "DELETE",
    url: useGetDeleteEventUrl(id).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
