/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetDashboardStatsQueryResponse,
  GetDashboardStats401,
} from "../types/GetDashboardStats.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function useGetGetDashboardStatsUrl() {
  const res = { method: "GET", url: `/api/admin/dashboard` as const };
  return res;
}

/**
 * @summary GET /admin/dashboard - Get dashboard statistics.
 * {@link /admin/dashboard}
 */
export async function useGetDashboardStats(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetDashboardStatsQueryResponse,
    ResponseErrorConfig<GetDashboardStats401>,
    unknown
  >({
    method: "GET",
    url: useGetGetDashboardStatsUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
