/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetRsvpStatusQueryResponse,
  GetRsvpStatus401,
} from "../types/GetRsvpStatus.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function useGetGetRsvpStatusUrl() {
  const res = { method: "GET", url: `/api/rsvp` as const };
  return res;
}

/**
 * @summary GET /rsvp - Get RSVP status for current guest.
 * {@link /rsvp}
 */
export async function useGetRsvpStatus(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetRsvpStatusQueryResponse,
    ResponseErrorConfig<GetRsvpStatus401>,
    unknown
  >({
    method: "GET",
    url: useGetGetRsvpStatusUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
