/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  GetSessionQueryResponse,
  GetSession401,
} from "../types/GetSession.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function useGetGetSessionUrl() {
  const res = { method: "GET", url: `/api/auth/session` as const };
  return res;
}

/**
 * @summary GET /auth/session - Get current session info.
 * {@link /auth/session}
 */
export async function useGetSession(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetSessionQueryResponse,
    ResponseErrorConfig<GetSession401>,
    unknown
  >({
    method: "GET",
    url: useGetGetSessionUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
