/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type { HealthQueryResponse } from "../types/Health.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function useGetHealthUrl() {
  const res = { method: "GET", url: `/api/health` as const };
  return res;
}

/**
 * {@link /health}
 */
export async function useHealth(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    HealthQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "GET", url: useGetHealthUrl().url.toString(), ...requestConfig });
  return res.data;
}
