/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  ListAdminEventsQueryResponse,
  ListAdminEvents401,
} from "../types/ListAdminEvents.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function useGetListAdminEventsUrl() {
  const res = { method: "GET", url: `/api/admin/events` as const };
  return res;
}

/**
 * @summary GET /admin/events - List all events for admin.
 * {@link /admin/events}
 */
export async function useListAdminEvents(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    ListAdminEventsQueryResponse,
    ResponseErrorConfig<ListAdminEvents401>,
    unknown
  >({
    method: "GET",
    url: useGetListAdminEventsUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
