/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type { LogoutMutationResponse } from "../types/Logout.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function useGetLogoutUrl() {
  const res = { method: "POST", url: `/api/auth/logout` as const };
  return res;
}

/**
 * @summary POST /auth/logout - Log out and clear session.
 * {@link /auth/logout}
 */
export async function useLogout(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    LogoutMutationResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "POST",
    url: useGetLogoutUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
