/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  ListGuestsQueryResponse,
  ListGuests401,
} from "../types/ListGuests.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function useGetListGuestsUrl() {
  const res = { method: "GET", url: `/api/admin/guests` as const };
  return res;
}

/**
 * @summary GET /admin/guests - List all guests with their invite codes and RSVP status.
 * {@link /admin/guests}
 */
export async function useListGuests(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    ListGuestsQueryResponse,
    ResponseErrorConfig<ListGuests401>,
    unknown
  >({
    method: "GET",
    url: useGetListGuestsUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
