/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type { ListEventsQueryResponse } from "../types/ListEvents.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function useGetListEventsUrl() {
  const res = { method: "GET", url: `/api/events` as const };
  return res;
}

/**
 * @summary GET /events - List all events ordered by display_order.
 * {@link /events}
 */
export async function useListEvents(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    ListEventsQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: useGetListEventsUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
