/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  RegenerateCodeMutationResponse,
  RegenerateCodePathParams,
  RegenerateCode401,
  RegenerateCode404,
} from "../types/RegenerateCode.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function useGetRegenerateCodeUrl(id: RegenerateCodePathParams["id"]) {
  const res = { method: "POST", url: `/api/admin/guests/${id}/code` as const };
  return res;
}

/**
 * @summary POST /admin/guests/:id/code - Generate a new invite code for a guest.
 * {@link /admin/guests/:id/code}
 */
export async function useRegenerateCode(
  id: RegenerateCodePathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    RegenerateCodeMutationResponse,
    ResponseErrorConfig<RegenerateCode401 | RegenerateCode404>,
    unknown
  >({
    method: "POST",
    url: useGetRegenerateCodeUrl(id).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
