/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  SubmitRsvpMutationRequest,
  SubmitRsvpMutationResponse,
  SubmitRsvp400,
  SubmitRsvp401,
} from "../types/SubmitRsvp.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function useGetSubmitRsvpUrl() {
  const res = { method: "POST", url: `/api/rsvp` as const };
  return res;
}

/**
 * @summary POST /rsvp - Submit or update RSVP.
 * {@link /rsvp}
 */
export async function useSubmitRsvp(
  data: SubmitRsvpMutationRequest,
  config: Partial<RequestConfig<SubmitRsvpMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    SubmitRsvpMutationResponse,
    ResponseErrorConfig<SubmitRsvp400 | SubmitRsvp401>,
    SubmitRsvpMutationRequest
  >({
    method: "POST",
    url: useGetSubmitRsvpUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
