/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  UpdateEventMutationRequest,
  UpdateEventMutationResponse,
  UpdateEventPathParams,
  UpdateEvent400,
  UpdateEvent401,
  UpdateEvent404,
} from "../types/UpdateEvent.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function useGetUpdateEventUrl(id: UpdateEventPathParams["id"]) {
  const res = { method: "PUT", url: `/api/admin/events/${id}` as const };
  return res;
}

/**
 * @summary PUT /admin/events/:id - Update an event.
 * {@link /admin/events/:id}
 */
export async function useUpdateEvent(
  id: UpdateEventPathParams["id"],
  data: UpdateEventMutationRequest,
  config: Partial<RequestConfig<UpdateEventMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    UpdateEventMutationResponse,
    ResponseErrorConfig<UpdateEvent400 | UpdateEvent401 | UpdateEvent404>,
    UpdateEventMutationRequest
  >({
    method: "PUT",
    url: useGetUpdateEventUrl(id).url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
