/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  UpdateGuestMutationRequest,
  UpdateGuestMutationResponse,
  UpdateGuestPathParams,
  UpdateGuest400,
  UpdateGuest401,
  UpdateGuest404,
} from "../types/UpdateGuest.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function useGetUpdateGuestUrl(id: UpdateGuestPathParams["id"]) {
  const res = { method: "PUT", url: `/api/admin/guests/${id}` as const };
  return res;
}

/**
 * @summary PUT /admin/guests/:id - Update a guest.
 * {@link /admin/guests/:id}
 */
export async function useUpdateGuest(
  id: UpdateGuestPathParams["id"],
  data: UpdateGuestMutationRequest,
  config: Partial<RequestConfig<UpdateGuestMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    UpdateGuestMutationResponse,
    ResponseErrorConfig<UpdateGuest400 | UpdateGuest401 | UpdateGuest404>,
    UpdateGuestMutationRequest
  >({
    method: "PUT",
    url: useGetUpdateGuestUrl(id).url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
