/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/axios";
import type {
  ValidateCodeMutationRequest,
  ValidateCodeMutationResponse,
  ValidateCode400,
} from "../types/ValidateCode.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";

function useGetValidateCodeUrl() {
  const res = { method: "POST", url: `/api/auth/code` as const };
  return res;
}

/**
 * @summary POST /auth/code - Validate an invite code and create a session.
 * {@link /auth/code}
 */
export async function useValidateCode(
  data: ValidateCodeMutationRequest,
  config: Partial<RequestConfig<ValidateCodeMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    ValidateCodeMutationResponse,
    ResponseErrorConfig<ValidateCode400>,
    ValidateCodeMutationRequest
  >({
    method: "POST",
    url: useGetValidateCodeUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
